"""Add MVP models: Organization and ProvenanceEvent

Revision ID: bc1724eaace5
Revises: 
Create Date: 2025-11-19 22:52:27.040986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1724eaace5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitrage_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gpu_type', sa.String(length=100), nullable=False),
    sa.Column('cheapest_provider', sa.String(length=50), nullable=True),
    sa.Column('cheapest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expensive_provider', sa.String(length=50), nullable=True),
    sa.Column('expensive_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spread_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbitrage_cache_gpu_type'), 'arbitrage_cache', ['gpu_type'], unique=False)
    op.create_index(op.f('ix_arbitrage_cache_timestamp'), 'arbitrage_cache', ['timestamp'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('gpus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'LEASED', 'MAINTENANCE', name='gpustatus'), nullable=True),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('g_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uptime_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('benchmark_score', sa.Integer(), nullable=True),
    sa.Column('power_consumption', sa.Integer(), nullable=True),
    sa.Column('max_power', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpus_available'), 'gpus', ['available'], unique=False)
    op.create_index(op.f('ix_gpus_external_id'), 'gpus', ['external_id'], unique=False)
    op.create_index(op.f('ix_gpus_model'), 'gpus', ['model'], unique=False)
    op.create_index(op.f('ix_gpus_provider'), 'gpus', ['provider'], unique=False)
    op.create_index(op.f('ix_gpus_status'), 'gpus', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='skilllevel'), nullable=True),
    sa.Column('theme_preference', sa.Enum('PROFESSIONAL', 'GAMING', 'CREATIVE', 'DEVELOPER', 'MINIMAL', 'CORPORATE', 'ACADEMIC', name='themepreference'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'FAILED', name='clusterstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_status'), 'clusters', ['status'], unique=False)
    op.create_table('provenance_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gpu_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('REGISTERED', 'STATUS_CHANGED', 'LEASED', 'RETURNED', 'MAINTENANCE_START', 'MAINTENANCE_END', name='provenanceeventtype'), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_events_created_at'), 'provenance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenance_events_event_type'), 'provenance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_provenance_events_gpu_id'), 'provenance_events', ['gpu_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gpu_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='reservationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_table('cluster_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('gpu_id', sa.UUID(), nullable=False),
    sa.Column('contribution_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'PAYMENT', 'REFUND', 'EARNING', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('cluster_members')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_provenance_events_gpu_id'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_event_type'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_created_at'), table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index(op.f('ix_clusters_status'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gpus_status'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_provider'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_model'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_external_id'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_available'), table_name='gpus')
    op.drop_table('gpus')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_arbitrage_cache_timestamp'), table_name='arbitrage_cache')
    op.drop_index(op.f('ix_arbitrage_cache_gpu_type'), table_name='arbitrage_cache')
    op.drop_table('arbitrage_cache')
    # ### end Alembic commands ###
